language: node_js
node_js:
  - node
before_install:
  - chmod +x ./scripts/master.sh
install: npm install
services: mongodb
cache:
  directories:
    - "node_modules"
env:
  - DB="mongodb://127.0.0.1/deca-wallet_test"

script:
  - npm run test
after_success:
  - ./scripts/master.sh

notifications:
  email: false
