language: node_js
node_js:
  - node
install: npm install
services: mongodb
cache:
  directories:
    - "node_modules"
env:
  - DB="mongodb://127.0.0.1/deca-wallet_test"

script:
  - npm run test
after_success:
  - |
    if [[ $TRAVIS_PULL_REQUEST == “false” ]] && [[ $TRAVIS_BRANCH == “master” ]]; then 
    COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls 
    fi

notifications:
  email: false
